properties
# ======================
# ??????? ?????????
# ======================
spring.application.name=resume
server.port=8080

# ======================
# Primary DataSource (???????? ??????????)
# ======================
spring.datasource.primary.jdbc-url=jdbc:postgresql://localhost:4999/db
spring.datasource.primary.username=user
spring.datasource.primary.password=12345
spring.datasource.primary.driver-class-name=org.postgresql.Driver

# ======================
# Secondary DataSource (Keycloak)
# ======================
spring.datasource.secondary.jdbc-url=jdbc:postgresql://localhost:5444/keycloak
spring.datasource.secondary.username=keycloak
spring.datasource.secondary.password=12345
spring.datasource.secondary.driver-class-name=org.postgresql.Driver

# ======================
# JPA / Hibernate
# ======================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# ???????? ??? ??????? ????????:
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# ======================
# Flyway (?????????)
# ======================
spring.flyway.enabled=false

# ======================
# ?????
# ======================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=177omega177@gmail.com
spring.mail.password=mysx trry gncp wqbk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ======================
# RabbitMQ
# ======================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=password

# ======================
# ???????????
# ======================
logging.file.name=logs/application.log
logging.level.root=INFO
logging.level.com.example.demo=DEBUG
logging.level.org.springframework.jdbc=DEBUG
logging.level.com.zaxxer.hikari=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# ======================
# ????????????
# ======================
spring.security.user.name=admin
spring.security.user.password=admin123
spring.security.user.roles=ADMIN


spring.security.oauth2.client.registration.keycloak.provider=keycloak
spring.security.oauth2.client.registration.keycloak.client-id=resume
spring.security.oauth2.client.registration.keycloak.client-name=resume
spring.security.oauth2.client.registration.keycloak.client-secret=yTFAL0CTounx5zj7PiAiiZTPEp1vajH8
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.scope=openid profile email
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/resume
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/realms/resume/protocol/openid-connect/certs

